### Read all users
GET http://localhost:4000/user-api/users

### Read user by ObjectID
GET http://localhost:4000/user-api/users/6983740f121d7717584c61d1

### Create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username" : "Spurthi",
    "password" : "spurthi",
    "age" : 20
}

### Update user
PUT http://localhost:4000/user-api/users/6983740f121d7717584c61d1
Content-Type: application/json

{
    "username" : "Spurthi",
    "password" : "spurthi123",
    "age" : 21
}

### Delete user
DELETE http://localhost:4000/user-api/users/6983740f121d7717584c61d1

### 
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid": 101,
    "productName": "Smartphone",
    "price": 30000
}

###
GET http://localhost:4000/product-api/products

###
GET http://localhost:4000/product-api/products/6983745c121d7717584c61d9

###
PUT http://localhost:4000/product-api/products/6983745c121d7717584c61d9
Content-Type: application/json

{
    "pid": 101,
    "productName": "Smartphone Pro",
    "price": 45000
}

### User authentication (login) req
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username" : "Spurthi",
    "password" : "spurthi",
    "age" : 20
}

### Req for protected route
GET http://localhost:4000/user-api/test